-- Databricks Schema for Interfaces Metrics Dashboard
-- Tables for storing performance metrics from grid/interfaces/

-- =============================================================================
-- Bridge Metrics Table
-- =============================================================================

CREATE TABLE IF NOT EXISTS interfaces_bridge_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    trace_id STRING NOT NULL,
    transfer_latency_ms DOUBLE,
    compressed_size BIGINT,
    raw_size BIGINT,
    compression_ratio DOUBLE,
    coherence_level DOUBLE,
    entanglement_count INT,
    integrity_check STRING,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    source_module STRING,
    metadata STRING, -- JSON string

    -- Indexes
    INDEX idx_timestamp (timestamp),
    INDEX idx_trace_id (trace_id),
    INDEX idx_source_module (source_module),
    INDEX idx_timestamp_success (timestamp, success)
)
USING DELTA
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
);

-- =============================================================================
-- Sensory Metrics Table
-- =============================================================================

CREATE TABLE IF NOT EXISTS interfaces_sensory_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    trace_id STRING NOT NULL,
    modality STRING NOT NULL, -- text, visual, audio, structured
    duration_ms DOUBLE,
    coherence DOUBLE,
    raw_size BIGINT,
    source STRING,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message STRING,
    metadata STRING, -- JSON string

    -- Indexes
    INDEX idx_timestamp (timestamp),
    INDEX idx_trace_id (trace_id),
    INDEX idx_modality (modality),
    INDEX idx_timestamp_modality (timestamp, modality),
    INDEX idx_timestamp_success (timestamp, success)
)
USING DELTA
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
);

-- =============================================================================
-- Metrics Summary Table (Aggregated)
-- =============================================================================

CREATE TABLE IF NOT EXISTS interfaces_metrics_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_bucket TIMESTAMP NOT NULL, -- Hourly bucket
    interface_type STRING NOT NULL, -- bridge or sensory
    total_operations BIGINT NOT NULL DEFAULT 0,
    successful_operations BIGINT NOT NULL DEFAULT 0,
    failed_operations BIGINT NOT NULL DEFAULT 0,
    avg_latency_ms DOUBLE,
    p50_latency_ms DOUBLE,
    p95_latency_ms DOUBLE,
    p99_latency_ms DOUBLE,
    avg_coherence DOUBLE,
    throughput_per_second DOUBLE,

    -- Additional aggregations for bridge
    avg_compression_ratio DOUBLE,
    avg_entanglement_count DOUBLE,

    -- Additional aggregations for sensory
    modality_distribution STRING, -- JSON string with modality counts

    -- Indexes
    INDEX idx_time_bucket (time_bucket),
    INDEX idx_interface_type (interface_type),
    INDEX idx_time_bucket_interface (time_bucket, interface_type),

    -- Unique constraint to prevent duplicate aggregations
    UNIQUE (time_bucket, interface_type)
)
USING DELTA
TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
);

-- =============================================================================
-- Views for Common Queries
-- =============================================================================

-- View: Recent Bridge Metrics (last 24 hours)
CREATE OR REPLACE VIEW interfaces_bridge_metrics_recent AS
SELECT
    *,
    CASE
        WHEN raw_size > 0 THEN compressed_size * 100.0 / raw_size
        ELSE 0.0
    END AS compression_percentage
FROM interfaces_bridge_metrics
WHERE timestamp >= CURRENT_TIMESTAMP() - INTERVAL 24 HOURS;

-- View: Recent Sensory Metrics (last 24 hours)
CREATE OR REPLACE VIEW interfaces_sensory_metrics_recent AS
SELECT
    *,
    CASE
        WHEN duration_ms > 0 THEN raw_size * 1000.0 / duration_ms
        ELSE 0.0
    END AS throughput_bytes_per_second
FROM interfaces_sensory_metrics
WHERE timestamp >= CURRENT_TIMESTAMP() - INTERVAL 24 HOURS;

-- View: Hourly Summary
CREATE OR REPLACE VIEW interfaces_metrics_hourly_summary AS
SELECT
    time_bucket,
    interface_type,
    total_operations,
    successful_operations,
    failed_operations,
    CAST(successful_operations * 100.0 / NULLIF(total_operations, 0) AS DOUBLE) AS success_rate_percentage,
    avg_latency_ms,
    p95_latency_ms,
    p99_latency_ms,
    throughput_per_second,
    avg_coherence
FROM interfaces_metrics_summary
ORDER BY time_bucket DESC;

-- View: Modality Distribution
CREATE OR REPLACE VIEW interfaces_sensory_modality_distribution AS
SELECT
    modality,
    COUNT(*) AS operation_count,
    AVG(duration_ms) AS avg_duration_ms,
    AVG(coherence) AS avg_coherence,
    SUM(CASE WHEN success THEN 1 ELSE 0 END) AS success_count,
    SUM(CASE WHEN NOT success THEN 1 ELSE 0 END) AS failure_count,
    CAST(SUM(CASE WHEN success THEN 1 ELSE 0 END) * 100.0 / COUNT(*) AS DOUBLE) AS success_rate_percentage
FROM interfaces_sensory_metrics
WHERE timestamp >= CURRENT_TIMESTAMP() - INTERVAL 7 DAYS
GROUP BY modality
ORDER BY operation_count DESC;

-- View: Performance Percentiles
CREATE OR REPLACE VIEW interfaces_performance_percentiles AS
SELECT
    interface_type,
    APPROX_PERCENTILE(
        CASE
            WHEN interface_type = 'bridge' THEN transfer_latency_ms
            WHEN interface_type = 'sensory' THEN duration_ms
            ELSE NULL
        END,
        ARRAY(0.5, 0.95, 0.99)
    ) AS percentiles,
    AVG(
        CASE
            WHEN interface_type = 'bridge' THEN transfer_latency_ms
            WHEN interface_type = 'sensory' THEN duration_ms
            ELSE NULL
        END
    ) AS avg_latency
FROM (
    SELECT 'bridge' AS interface_type, transfer_latency_ms, NULL AS duration_ms
    FROM interfaces_bridge_metrics
    WHERE timestamp >= CURRENT_TIMESTAMP() - INTERVAL 24 HOURS
    UNION ALL
    SELECT 'sensory' AS interface_type, NULL AS transfer_latency_ms, duration_ms
    FROM interfaces_sensory_metrics
    WHERE timestamp >= CURRENT_TIMESTAMP() - INTERVAL 24 HOURS
) AS combined_metrics
GROUP BY interface_type;

-- =============================================================================
-- Comments
-- =============================================================================

COMMENT ON TABLE interfaces_bridge_metrics IS 'Performance metrics for QuantumBridge transfer operations';
COMMENT ON TABLE interfaces_sensory_metrics IS 'Performance metrics for SensoryProcessor operations';
COMMENT ON TABLE interfaces_metrics_summary IS 'Aggregated metrics summary by hour and interface type';

COMMENT ON COLUMN interfaces_bridge_metrics.compression_ratio IS 'Compressed size / raw size ratio';
COMMENT ON COLUMN interfaces_bridge_metrics.coherence_level IS 'Coherence level (0.0-1.0)';
COMMENT ON COLUMN interfaces_sensory_metrics.modality IS 'Input modality: text, visual, audio, or structured';
COMMENT ON COLUMN interfaces_sensory_metrics.coherence IS 'Processing coherence factor (0.0-1.0)';
COMMENT ON COLUMN interfaces_metrics_summary.time_bucket IS 'Hourly time bucket for aggregation';
